### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-cli-runner#185]
- [x] webignition/basil-cli-compiler#259
- [x] webignition/basil-phpunit-result-printer#140
- [x] webignition/tcp-cli-proxy-client#44
- [x] webignition/tcp-cli-proxy-models#9
